// webapp-svelte/src/SessionView.svelte
<style>
    dl {
        width: 600px;
        overflow: hidden;
        padding: 0;
        margin: 0
    }
    dt {
        float: left;
        width: 50%;
        padding: 0;
        margin: 0
    }
    dd {
        float: left;
        width: 50%;
        padding: 0;
        margin: 0;
    }
</style>
<script>
    import { onMount, onDestroy, createEventDispatcher } from 'svelte'

    import Login from './Login.svelte';
    import RoomView from './RoomView.svelte'
    import { messages } from './stores.js'

    export let session;

    let connected = false
    let sessionId = null;
    let profile = null;
    let authenticated = false;

    $: rooms = [];
    let myrooms = [];
    let participantsByRoom = {};
    let receivedMessagesByRoom = {};

    let messagesByRoom = {}


    session.onAuthenticated.add(() => {
        authenticated = true;
        session.join('default');
        session.join('test');
    });

    session.onRoomList.add(r => rooms = r);
    session.onMyRoomList.add(r=>  myrooms = r );
    session.onProfile.add(p => profile = p)

    session.onMessage.add(({room, message}) => {
        messages.update(messagesByRoom => {
            const roomMessages = [...(messagesByRoom[room]||[]), message];
            return {
                ...messagesByRoom,
                [room]: roomMessages
            }
        });
    });

    async function connect() {
        console.info("connect()")
        session.onWelcome.add(() => { console.debug('/0\\', session) });
        const sessionDescription = await session.connect();
        sessionId = sessionDescription.sessionId
        connected = true;

        session.sendCommand({ type: 'listRooms' });
        session.sendCommand({ type: 'listMyRooms' });
        session.authenticate('jon', 'password')
    }

    function send({detail: {message, currentRoom}}) {
        session.sendMessage(message, currentRoom);
    }

	onMount(async () => {
        console.debug("mounted", session)
        window.session = session
        await connect();
    });
    onDestroy(() => {
        console.debug("destroy", session)
        session.disconnect()
    });

</script>

<h2> SessionView </h2>

<aside>
<dl>
    <dt>connected</dt>
    <dd>{connected}</dd>

    <dt>sessionId</dt>
    <dd>{sessionId}</dd>

    <dt>authenticated</dt>
    <dd>{authenticated}</dd>

    <dt>user</dt>
    <dd>{profile && profile.fullName}</dd>
</dl>
</aside>

{#if !connected}
    <button on:click={connect}> connect </button>
{:else}
    {#if !authenticated}
        <Login on:login={({detail: {username, password}}) => session.authenticate(username, password)} />
    {:else}
        <RoomView 
            sessionId={sessionId}
            rooms={myrooms}
            messagesByRoom={messagesByRoom}
            on:send={send}
        />
    {/if}
{/if}

// webapp/src/SessionView.tsx
import * as React from 'react';

import { Session, SessionDescription, ChatMessage } from '../../client-lib/';
import { SendForm } from './SendForm';
import { AuthenticatedView } from './AuthenticatedView';
import { UserProfile, Participant } from '../../client-lib/src/protocol';
import { MessageList } from './MessageViews';
import { RoomSelector } from './RoomSelector';

export interface SessionViewProps {
    session: Session;
    onDisconnect: () => void;
}

interface SessionViewState {
    authenticated: boolean,
    rooms: string[];
    myrooms: string[];
    participantsByRoom: {[room: string]: Array<Participant>};
    roomToSendTo: string;
    roomToJoin: string;
    receivedMessagesByRoom: { [index: string]: ChatMessage[] },

    profile?: UserProfile;
    sessionDescription?: SessionDescription;
}

export class SessionView extends React.Component<SessionViewProps, SessionViewState> {
    private session: Session;
    private lastMessage?: HTMLSpanElement;

    constructor(props: SessionViewProps) {
        super(props);
        this.state = {
            authenticated: false,
            rooms: [],
            myrooms: [],
            participantsByRoom: {},
            receivedMessagesByRoom: {},
            roomToJoin: "default",
            roomToSendTo: "default"
        };
        this.session = props.session;

        this.session.onWelcome.add(sessionDescription => {
            this.setState({ sessionDescription })
            this.session.sendCommand({ type: 'listRooms' });
            this.session.sendCommand({ type: 'listMyRooms' });
            // this.session.authenticate('hendrik', 'password');
        });

        this.session.onAuthenticated.add(() => {
            this.setState({ authenticated: true });
            this.session.join('default');
        })

        this.session.onProfile.add(profile => this.setState({profile}));

        this.session.onConnectionClose.add(event => {
            console.error(event);
            this.props.onDisconnect();
        });

        this.session.onRoomList.add(rooms => {
            console.debug("onRoomList", rooms)
            this.setState({rooms})
        });

        this.session.onMyRoomList.add(myrooms => {
            console.debug("onMyRoomList", myrooms)
            this.setState({ myrooms })
        });

        this.session.onRoomParticipants.add(({room, participants}) => {
            let participantsByRoom = {...this.state.participantsByRoom, [room]: participants};
            this.setState({participantsByRoom})
        });

        this.session.onMessage.add(({ message, room }) => {
            console.debug(room, message)
            const receivedMessagesByRoom = {...this.state.receivedMessagesByRoom };
            const oldRoomMessages = receivedMessagesByRoom[room] || [];
            receivedMessagesByRoom[room] = [...oldRoomMessages, message]
            console.debug({receivedMessagesByRoom})
            this.setState({ receivedMessagesByRoom })
            this.lastMessage!.scrollIntoView({ behavior: "smooth" });
        });

        this.session.onError.add(alert);

        (window as any).session = this.session;
    }

    private roomToJoin: React.ChangeEventHandler<HTMLInputElement> = ({ target: { value } }) => {
        this.setState({ roomToJoin: value })
    };

    private sendToRoom = (content: string) => {
        this.session.sendMessage(content, this.state.roomToSendTo)
    };

    // TODO: temporary
    componentDidMount = () => {
        console.debug("mounted")
        // this.session.connect();
    };

    private connectionView = () => {
        if (this.state.sessionDescription) {
            return (
                <React.Fragment>
                    <aside>
                        <h4>my rooms</h4>
                        <RoomSelector rooms={this.state.myrooms} onSelect={roomToSendTo => this.setState({ roomToSendTo })} />
                        <ul> {
                        (this.state.participantsByRoom[this.state.roomToSendTo] || [])
                            .map(participant => <li key={participant.sessionId}>{participant.fullName}</li>)
                        }</ul>
                    </aside>

                    <section>
                        <div className="messageBox">
                            <div>
                                <MessageList
                                    messages={this.state.receivedMessagesByRoom[this.state.roomToSendTo] || []}
                                    me={this.state.sessionDescription.sessionId}/>
                                <span ref={e => this.lastMessage = !e ? undefined : e} ></span>
                            </div>
                        </div>
                        <SendForm onSend={this.sendToRoom} />
                    </section>

                    <nav>
                        <small>
                            <dl>
                                <dt>Username</dt>
                                <dd>{this.state.profile && this.state.profile.fullName}</dd>
                                <dt>SessionId</dt>
                                <dd><pre>{this.state.sessionDescription.sessionId}</pre></dd>
                            </dl>

                        </small>

                        <AuthenticatedView authenticated={this.state.authenticated} onsubmit={(u, p) => this.session.authenticate(u, p)}>
                            <h6> join room </h6>

                            <RoomSelector rooms={this.state.rooms} onSelect={room => { this.session.join(room) }} />
                            <input
                                type="text" name="channelName" id="channelName"
                                onChange={this.roomToJoin} placeholder="createNew" />
                            <button onClick={() => this.session.join(this.state.roomToJoin)}> join </button>
                        </AuthenticatedView>

                        <hr />
                        <button onClick={this.disconnect}> disconnect </button>

                    </nav>
                </React.Fragment>
            )
        } else {
            return <button onClick={() => this.session.connect()}> connect </button>
        }
    };

    private disconnect = () => {
        this.session.disconnect();
        this.props.onDisconnect();
    }

    render() {
        return (
            <div className="sessionView">
                {this.connectionView()}
            </div>
        )
    }
}
